name: Minify CSS

on:
  push:
    branches:
      - master

jobs:
  minify-css:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install html-minifier clean-css-cli
      
    - name: Minify CSS files
      run: |
        find css -type f -name '*.css' -exec npx cleancss --output {} {} \;

    - name: Minify HTML files
      run: |
        npx html-minifier --input-dir ./ --output-dir ./ --file-ext html --collapse-whitespace --remove-comments
    
    - name: List files in directory
      run: tree .
      
    - name: Show contents of a file
      run: cat index.html

    - name: show contents of a file
      run: cat css/main.css
    
    - name: show contents of a file
      run: cat css/1/1.css
      
    - name: Create ZIP archive
      run: |
        zip -r ../minified.zip *

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v2
      with:
        name: minified
        path: minified.zip
      
      
